### PR TITLE
Add initial dockerfile for Hawkular BTM server

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
Not published to docker hub yet - need to find out who to talk to about that.

**Comment by goldmann** [comment]
That would be me ;)

**Comment by objectiser** [comment]
@goldmann Ok good to know. Once the PR has been reviewed (I guess by someone on the hawkular team), I'll ping you.

**Comment by objectiser** [comment]
@goldmann should be ready to publish to dockerhub - let me know if you need any further info. Thanks.

**Comment by goldmann** [comment]
Done, a tagged version will be triggered when the repo will be tagged.

**Comment by goldmann** [comment]
Forgot to add the link: https://hub.docker.com/r/jboss/hawkular-btm/

**Comment by objectiser** [comment]
@goldmann thanks

**Pull request merged**
