### PR TITLE
HWKAPM-462 - Added APM image for dev

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@objectiser : it's ready for review/test.

**Comment by objectiser** [comment]
@jpkrohling Seems to work great. Only comment is can you update the top level readme just to include the new image name (and description). Once done ask Thomas to merge.

**Comment by jpkrohling** [comment]
Added. The link is broken, though. Is this automatically created once this new directory is added, or should something be done on Docker Hub?

**Comment by objectiser** [comment]
It should be added once published to docker hub.

**Comment by jpkrohling** [comment]
@theute , would you please merge this one?

**Pull request merged**
