### PR TITLE
Rename from BTM to APM.

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@theute Hi Thomas, if you could review/merge when you get a chance - I know you are going to be busy, good luck with the demo :)

**Comment by objectiser** [comment]
@goldmann Would you be able to publish this change to dockerhub? Note that the name has changed from hawkular-btm to hawkular-apm-server. Thanks in advance.

**Comment by goldmann** [comment]
Done!

**Comment by objectiser** [comment]
@goldmann Thanks!

**Pull request merged**
