### PR TITLE
Added service deployment to OpenShift

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
This is based on the template, but instead of creating templates to be used as "instant app", this actually creates the service. It ships with a default fixed `admin` and `password`, not a randomly generated password. We might either not specify the password, and let our `wrapper.sh` create and print it to the console (and add instructions on how to find it), or we make it consistent with the other services (like Jenkins). For now, I've chosen the "consistent" path.

**Comment by jpkrohling** [comment]
@objectiser , this goes together with the MSA changes.

**Comment by objectiser** [comment]
@jpkrohling Looks reasonable to me, but would it be possible to get someone from cloud enablement or openshift teams to review/advise?

**Comment by jpkrohling** [comment]
@goldmann , would it be possible to review or assign someone to review this? Also, we talked on IRC some time ago about the most appropriate location for such files, and I just wanted to confirm that this is still the case :)

**Comment by objectiser** [comment]
@jpkrohling Thanks!

**Pull request merged**
