### PR TITLE
Small fixes and adaptations for OpenShift

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@objectiser , would you please review/merge this one?

**Comment by objectiser** [comment]
@jpkrohling LGTM :+1: 

Do you want to add you details to maintainers? may be next time you update.

**Comment by jpkrohling** [comment]
If @pavolloffay is also able to merge, there's no need for me to be a maintainer, as I'd always ask for a review anyway :)

**Comment by pavolloffay** [comment]
@jpkrohling I should have merge rights. I can review next time.

**Comment by objectiser** [comment]
@jpkrohling Was thinking more from the perspective of who is the expert :) If anyone has any questions they would probably first ask the person listed as the maintainer. But happy to leave as is.

**Pull request merged**
