### PR TITLE
First attempt

### PR DESCRIPTION
**Pull request by theute**

### CODE REVIEW

**Comment by goldmann** [comment]
Do you have a version that could be extracted on top of WildFly and using the `jboss/wildfly` image as base?

**Comment by theute** [comment]
Good idea, but not at this point, the 'layering' is quite complex on top of wildfly

**Comment by theute** [comment]
@goldmann ^

**Comment by goldmann** [comment]
OK, merging.

**Comment by goldmann** [comment]
Build triggered, feel free to join #jboss-docker on Freenode.

**Pull request merged**
