### PR TITLE
Added OpenShift Template for Hawkular APM

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
As discussed with @goldmann , there's no problem in having one build per commit, so, this file can change at will without undesired side effects.

**Comment by jpkrohling** [comment]
@objectiser , @pavolloffay , could you please review it? It's still missing the liveness/readiness probes, but those can be added at a later commit.

**Comment by objectiser** [comment]
@jpkrohling LGTM, although I think the file should be renamed `hawkular-apm-server.yml`.

Is it worth asking for comments from the openshift team? Possibly Clayton?

**Comment by jpkrohling** [comment]
cc @smarterclayton

**Comment by jpkrohling** [comment]
Perhaps this should have been sent to https://github.com/jboss-openshift/application-templates instead?

**Comment by pavolloffay** [comment]
@jpkrohling LGTM :+1: , Is the APM port configurable? If not what do you think about making it configurable? (someone who is using zipkin can quickly switch to APM) @objectiser what do you think?

**Comment by jpkrohling** [comment]
A service using ZipKin would use the port 80, referencing only the host. Similarly, a service using APM would also access it via the port 80, and OpenShift would expose our 8080 as 80.

**Pull request merged**
