### PR TITLE
Update APM to version 0.10.0.Final

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@theute Tested locally, and works fine - if you can merge when you get a chance. Thanks.

**Comment by objectiser** [comment]
@goldmann Hi Marek, would you be able to push the hawkular-apm-server and hawkular-apm-server-dev images to dockerhub please?

**Comment by goldmann** [comment]
`hawkular-apm-server` should be already built, `hawkular-apm-server-dev` is hooked and triggered.

**Comment by objectiser** [comment]
@goldmann ok great, thanks. So from now on, we only need to push changes to the git repo and it will automatically be available via dockerhub?

**Comment by goldmann** [comment]
ACK

**Pull request merged**
